abstract: Perl-compatible regular expressions
author: Audrey Tang
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: re-engine-PCRE
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.9.5
version: 0.03
