--- #YAML:1.0
name:                re-engine-PCRE
version:             0.09
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31_01
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
